services:
    _defaults:
        autowire: true
        autoconfigure: true

    HeimrichHannot\SimpleMemberChatBundle\:
        resource: ../src/
        exclude: ../src/{Configuration,ContaoManager,Domain,Event,Exception,HeimrichHannotSimpleMemberChatBundle.php}

    HeimrichHannot\SimpleMemberChatBundle\Service\ContactPermissionInterface:
        alias: HeimrichHannot\SimpleMemberChatBundle\Service\DenyContactPermission

    HeimrichHannot\SimpleMemberChatBundle\Gateway\ConversationGatewayInterface:
        alias: HeimrichHannot\SimpleMemberChatBundle\Gateway\ConversationGateway

    HeimrichHannot\SimpleMemberChatBundle\Gateway\ParticipantGatewayInterface:
        alias: HeimrichHannot\SimpleMemberChatBundle\Gateway\ParticipantGateway

    HeimrichHannot\SimpleMemberChatBundle\Gateway\MessageGatewayInterface:
        alias: HeimrichHannot\SimpleMemberChatBundle\Gateway\MessageGateway
